# Generated by Django 5.1.5 on 2025-01-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
                ("contact", models.IntegerField()),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        # migrations.CreateModel(
        #     name="Predictions",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("condition", models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name="CheckUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("sex", models.IntegerField()),
                ("cp", models.IntegerField()),
                ("trestbps", models.IntegerField()),
                ("chol", models.IntegerField()),
                ("fbs", models.IntegerField()),
                ("restecg", models.IntegerField()),
                ("thalach", models.IntegerField()),
                ("exang", models.IntegerField()),
                ("oldpeak", models.FloatField()),
                ("slope", models.IntegerField()),
                ("ca", models.IntegerField()),
                ("thal", models.IntegerField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="HealthAI.patients",
                    ),
                ),
            ],
        ),
    ]
