# Generated by Django 4.2.20 on 2025-04-22 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkup',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='username',
        ),
        migrations.AddField(
            model_name='checkup',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthAI.patients'),
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
