# Generated by Django 5.2.1 on 2025-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthAI', '0002_remove_checkup_username_remove_patients_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
